### ISSUE TITLE
there is no support for embedding SVGs

### ISSUE THREAD

**Issue by rogpeppe** [ajstarks/svgo#17]
It is not uncommon to want to embed SVG data inside an SVG.
For example, see this PR: https://github.com/juju/jujusvg/pull/8/files
In that PR, some SVGs have been produced by our design team,
and we want to use them as part of the higher level SVG generation.
We have manually translated them to svgo code, but that's obviously
not ideal. I've considered making a little parser to parse the SVG
and emit svgo calls, but that's not ideal - we're really just translating
one format to itself.

Perhaps a "RawSVG" call might work here - it could perhaps do some
XML processing (strip off the outer <xml> element) or perhaps just
write the exact bytes given.

**Comment by ajstarks** [comment]
ping.  Ok to close?
