### ISSUE TITLE
No function for inserting <style type="text/css">

### ISSUE THREAD

**Issue by ookpalm** [ajstarks/svgo#19]
I believe there is a way to add the tag "style" into SVG like this \<style type="text/css">...\</script> However, I found only Script(string, string) function which can not be used for styling. I really don't know which function can be used for making style tag or it is really not there?

**Comment by ajstarks** [comment]
You have access to the io.Writer for the SVG you are generating, so you can inject arbitrary code at any time.

<pre>
package main

import (
	"os"
	"io"
	"github.com/ajstarks/svgo"
)

func main() {

	css := `<style type="text/css"><![CDATA[
      rect {
        fill: red;
        stroke: blue;
        stroke-width: 3
      }]]></style>
      `
	canvas := svg.New(os.Stdout)
	canvas.Start(1000, 1000)
	canvas.Def()
	io.WriteString(canvas.Writer, css)
	canvas.DefEnd()
	canvas.Rect(200, 100, 600, 300)
	canvas.End()
}
</pre>

**Comment by ajstarks** [comment]
Also the conventional way is to use Gstyle()/Gend()

**Comment by ookpalm** [comment]
Thank you ajstarks for your kind support.
