### ISSUE TITLE
can this convert SVG to PNG?

### ISSUE THREAD

**Issue by gedw99** [ajstarks/svgo#23]

**Comment by ajstarks** [comment]
Batik SVG Rasterizer: https://xmlgraphics.apache.org/batik/tools/rasterizer.html
Inkscape command line: http://tavmjong.free.fr/INKSCAPE/MANUAL/html/CommandLine-Export.html

**Comment by gedw99** [comment]
Waht about a pure golang one ? DOnt want to depend on other libs.

**Comment by ajstarks** [comment]
I don't know of a pure Go SVG rasterizer.

**Comment by gedw99** [comment]
ok thanks for response.
Might have to just give up and do the imagemagic thing

**Comment by ajstarks** [comment]
Although not a SVG rasterizer, there is GIFT (Go Image Filtering Toolkit)  

https://github.com/disintegration/gift
https://github.com/ajstarks/gift

which may be helpful in doing tasks that you would use ImageMagic for.

**Comment by gedw99** [comment]
great - thanks. Will have a look now.
