### ISSUE TITLE
No floating-point-constants in polyline coordinates possible

### ISSUE THREAD

**Issue by fawick** [ajstarks/svgo#30]
From what I understood from https://www.w3.org/TR/SVG11/shapes.html#PointsBNF, the coordinates for polylines and polygons may consist of floating point numbers.

I wonder why svgo uses `[]int` instead of `[]float` in `func (svg *SVG) Polyline(x []int, y []int, s ...string)`.

**Comment by ajstarks** [comment]
You may use the svgo/float package.

**Comment by fawick** [comment]
Oh, cool, thanks, that's just what I was looking for! I did not grok that `./float` was not yet another example.
