### ISSUE TITLE
Support embedded style

### ISSUE THREAD

**Issue by yangzh** [ajstarks/svgo#31]
SVGo is nice, however, for my use, I cannot find support for embedded CSS.

The closest thing I can find is SVG.Script(), I guess we should have SVG.Style(), that add a CSS section inside a DEF section: supporting CSS is also part of SVG 1.1 spec.

**Comment by ajstarks** [comment]
Question: do you want to just embed raw CSS, or provide some API?

**Comment by yangzh** [comment]
Currently I'm interested in embeding raw CSS, and will be happy if svgo can add that.

Not sure what you mean by API, but that can delay, I guess.

**Comment by ajstarks** [comment]
See  revision 19107c6 and f4dea3d
