### ISSUE TITLE
Internal tools documentation, distribution, and features 

### ISSUE THREAD

**Issue by neonsoftware** [ajstarks/svgo#32]
Hi !
Great job, I really like the library. 

How do you see space for eventual addition of documentation, features, and distribution channel to the internal tools ? They are distributed only though go, right ?

More practically I will be focused on svgrid, (neat!) which I will mostly use among the others, but I can foresee that I might need to:
- extend it with some feature here and there
- extend its command-line usage documentation
- arrange a cross-platform distribution (win binary, linux via apt-get, brew on mac) and a CI.

These things might be, of course, done on the application side, but if you would be interested and they are something that you might merge, than I might design them to be generic, work directly on sigrid.go, and bring them upstream to the library, and other might use them. 
With a CI and distribution setup done for svgrid, then of course, all the other tools might jump on the wagon as well.

Thank you in advance and thank you for sharing the library 👍

**Comment by ajstarks** [comment]
Thanks, I'm glad the library is useful for you.

If you have updates, please send them, and I will evaluate for inclusion. At this point I don't have any plans for binary distributions.
