### ISSUE TITLE
Including units and floating point values

### ISSUE THREAD

**Issue by ryankurte** [ajstarks/svgo#42]
Hey, thanks for making a neat package!

I might have missed this feature, but, have you considered support for floating point and specified unit types (eg. `x=10.5cm`) ? 

Happy to do the refactor to replace the instances of int with a float/unit type if you'd be interested.

Cheers,

Ryan

**Comment by ajstarks** [comment]
Thanks for the kind words.

Floating point is supported:  import github.com/ajstarks/svgo/float
To specify units use Startunit or StartviewUnit

**Comment by ryankurte** [comment]
Thanks for the help! I had found StartUnit but not /float so was very confused about how to set fractional parts.
