### ISSUE TITLE
Defining marker orientation

### ISSUE THREAD

**Issue by DavidGamba** [ajstarks/svgo#51]
Is there a way to define marker orientation?
The Marker method only takes in style.

**Comment by ajstarks** [comment]
you can:

1) apply the needed transformations on the elements that make up the marker

```
        canvas.Marker("arrow", 2, 6, 13, 13)
	canvas.Path("M2,2 L2,11 L10,6 L2,2", `fill="blue"`,  `transform="rotate(-30)"`)
	canvas.MarkerEnd()
	canvas.DefEnd()
```

2) or apply the transformation when defining the marker:
```
        canvas.Marker("arrow", 2, 6, 13, 13)
	canvas.Rotate(-20)
	canvas.Path("M2,2 L2,11 L10,6 L2,2", `fill="blue"`)
	canvas.MarkerEnd()
	canvas.Gend()
	canvas.DefEnd()
```

**Comment by DavidGamba** [comment]
So `orient=auto` is not supported. Is that correct?
By the way I love your library (was going to give you a shout out on twitter), it is amazing how complete and well done it is.

**Comment by ajstarks** [comment]
Ah I see.   Note that you can add this:

``` canvas.Marker(..... , `orient="auto"`)```

This "escape hatch" is common to most methods.  
Many thanks for the kind words (A twitter shout out would be nice).

**Comment by DavidGamba** [comment]
That did it, thanks so much!
