### ISSUE TITLE
Requesting support for tspan

### ISSUE THREAD

**Issue by Iriel** [ajstarks/svgo#55]
Thanks for the useful library, one thing I found missing (and had to hack together myself) was support for tspan - as I was trying to center text with mixed styling.

This is what I ended up with in non-method form (the _svg functions are my replicas of the svgo private methods)

``` golang
func startText(canvas *svg.SVG, x int, y int, s ...string) {
	_svg_printf(canvas, `<text %s %s`, _svg_loc(x, y), _svg_endstyle(s, ">"))
}

func addText(canvas *svg.SVG, t string, s ...string) {
	if len(s) == 0 {
		xml.Escape(canvas.Writer, []byte(t))
		return
	}
	_svg_printf(canvas, `<tspan %s`, _svg_endstyle(s, ">"))
	xml.Escape(canvas.Writer, []byte(t))
	_svg_printf(canvas, "</tspan>")
}

func endText(canvas *svg.SVG) {
	_svg_println(canvas, "</text>")
}
```

**Comment by ajstarks** [comment]
This looks interesting.  Am I correct that this API could replace the Text method with startText... addText ... endText?
Can you provide a usage example?  Also, perhaps addText should be Tspan?

**Comment by ajstarks** [comment]
Example use: 
```
package main

import (
	"os"

	svg "github.com/ajstarks/svgo"
)

func main() {
	width := 500
	height := 500
	canvas := svg.New(os.Stdout)
	canvas.Start(width, height)
	canvas.Circle(width/2, height/2, 100)
	canvas.Gstyle("text-anchor:middle;fill:white")
	canvas.Textspan(width/2, height/2, "Hello ", "font-size:30px")
	canvas.Span("SVG", "font-size:50px")
	canvas.TextEnd()
	canvas.Gend()
	canvas.End()
}
```

![image](https://user-images.githubusercontent.com/169692/113717552-ba153400-96b9-11eb-84bd-d87fb1d67599.png)

**Comment by ajstarks** [comment]
Added with https://github.com/ajstarks/svgo/commit/1f3ef52b4e33b96dd34ef41022003ee149f96de5

**Comment by Iriel** [comment]
Lovely thanks!
