### ISSUE TITLE
Please add LICENSE

### ISSUE THREAD

**Issue by ghost** [ajstarks/svgo#68]
Hi,

Please, consider adding a LICENSE to avoid ambiguity!

Thank you in advance!

**Comment by ernierasta** [comment]
I am not sure if I understand question, but there is LICENSE file unchanged for two years now ... [CC-BY-4.0](https://github.com/ajstarks/svgo/blob/master/LICENSE)

**Comment by ghost** [comment]
/facepalm
Sorry, my bad, got distracted by GitHub reporting "Unknown" license. Carry on, nothing to see here (apart of ashamed person).

**Comment by ernierasta** [comment]
Hey! Nothing to be ashamed of! Have a great weekend!
